//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAS24.Libs.Localization.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BAS24.Libs.Localization.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        internal static string contact_request_1 {
            get {
                return ResourceManager.GetString("contact_request_1", resourceCulture);
            }
        }
        
        internal static string live_location_1 {
            get {
                return ResourceManager.GetString("live_location_1", resourceCulture);
            }
        }
        
        internal static string map_place_approved_1 {
            get {
                return ResourceManager.GetString("map_place_approved_1", resourceCulture);
            }
        }
        
        internal static string map_place_created_1 {
            get {
                return ResourceManager.GetString("map_place_created_1", resourceCulture);
            }
        }
        
        internal static string map_place_created_2 {
            get {
                return ResourceManager.GetString("map_place_created_2", resourceCulture);
            }
        }
        
        internal static string map_place_removed_1 {
            get {
                return ResourceManager.GetString("map_place_removed_1", resourceCulture);
            }
        }
        
        internal static string share_timeline_1 {
            get {
                return ResourceManager.GetString("share_timeline_1", resourceCulture);
            }
        }
    }
}
